from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

from version_info.model import State
from version_info.registry_cargo import _parse_cargo_lock, crates_io_latest, scan_cargo
from version_info.util_http import HttpResult


def test_parse_cargo_lock_basic() -> None:
    """Test parsing basic Cargo.lock file with multiple dependencies."""
    cargo_lock = """
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "anyhow"
version = "1.0.75"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "a4668cab20f66d8d020e1fbc0ebe47217433c1b6c8f2040faf858554e394ace6"

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "25dd9975e68d0cb5aa1120c288333fc98731bd1dd12f561e468ea4728c042b89"

[[package]]
name = "tokio"
version = "1.35.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "841d45b238794f6844726f1f0d17be33dfc28f637aa6a1e7e88b0d8e7b0c9c6d"
    """.strip()

    deps = _parse_cargo_lock(cargo_lock)

    assert len(deps) == 3
    # Should be sorted alphabetically
    assert deps[0].name == "anyhow"
    assert deps[0].version == "1.0.75"
    assert deps[1].name == "serde"
    assert deps[1].version == "1.0.193"
    assert deps[2].name == "tokio"
    assert deps[2].version == "1.35.0"


def test_parse_cargo_lock_empty() -> None:
    """Test parsing empty Cargo.lock file."""
    cargo_lock = """
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3
    """.strip()

    deps = _parse_cargo_lock(cargo_lock)

    assert len(deps) == 0


def test_parse_cargo_lock_with_dependencies() -> None:
    """Test parsing Cargo.lock with packages that have dependencies."""
    cargo_lock = """
[[package]]
name = "syn"
version = "2.0.39"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "23e78b90f2fcf45d3e842032ce32e3f2d1545ba6636271dcbf24fa306d87be7a"
dependencies = [
 "proc-macro2",
 "quote",
 "unicode-ident",
]

[[package]]
name = "quote"
version = "1.0.33"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5267fca4496028628a95160fc423a33e8b2e6af8a5302579e322e4b520293cae"
    """.strip()

    deps = _parse_cargo_lock(cargo_lock)

    assert len(deps) == 2
    assert deps[0].name == "quote"
    assert deps[0].version == "1.0.33"
    assert deps[1].name == "syn"
    assert deps[1].version == "2.0.39"


def test_parse_cargo_lock_with_workspace_package() -> None:
    """Test parsing Cargo.lock that includes workspace root package.

    Workspace-local packages (no source field) are excluded — only registry deps are kept.
    """
    cargo_lock = """
[[package]]
name = "my-project"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "25dd9975e68d0cb5aa1120c288333fc98731bd1dd12f561e468ea4728c042b89"
    """.strip()

    deps = _parse_cargo_lock(cargo_lock)

    # Workspace-local package (no source) is excluded; only registry dep is kept
    assert len(deps) == 1
    assert deps[0].name == "serde"
    assert deps[0].version == "1.0.193"


def testcrates_io_latest_success() -> None:
    """Test successful latest version fetch from crates.io."""
    mock_response = HttpResult(
        ok=True,
        status=200,
        text=json.dumps({"crate": {"max_version": "1.0.195"}}),
    )
    mock_json_data = {"crate": {"max_version": "1.0.195"}}

    with patch(
        "version_info.registry_cargo.get_json", return_value=(mock_response, mock_json_data)
    ):
        artifact, state = crates_io_latest("serde", timeout_s=10.0)

    assert state == State.ok
    assert artifact.value == "1.0.195"
    assert artifact.url == "https://crates.io/api/v1/crates/serde"


def testcrates_io_latest_not_found() -> None:
    """Test 404 handling for crates.io API."""
    mock_response = HttpResult(ok=False, status=404, text="not found", error="HTTP Error 404")

    with patch("version_info.registry_cargo.get_json", return_value=(mock_response, None)):
        artifact, state = crates_io_latest("nonexistent-crate", timeout_s=10.0)

    assert state == State.not_found
    assert artifact.value is None
    assert artifact.note == "not found"


def testcrates_io_latest_auth_required() -> None:
    """Test 401/403 handling for crates.io API."""
    mock_response = HttpResult(ok=False, status=403, text="forbidden", error="HTTP Error 403")

    with patch("version_info.registry_cargo.get_json", return_value=(mock_response, None)):
        artifact, state = crates_io_latest("some-crate", timeout_s=10.0)

    assert state == State.auth_required
    assert artifact.value is None
    assert artifact.note == "auth required"


def testcrates_io_latest_rate_limited() -> None:
    """Test 429 handling for crates.io API."""
    mock_response = HttpResult(
        ok=False, status=429, text="too many requests", error="HTTP Error 429"
    )

    with patch("version_info.registry_cargo.get_json", return_value=(mock_response, None)):
        artifact, state = crates_io_latest("some-crate", timeout_s=10.0)

    assert state == State.rate_limited
    assert artifact.value is None
    assert artifact.note == "rate limited"


def testcrates_io_latest_no_max_version() -> None:
    """Test error handling when max_version is missing from crates.io response."""
    mock_response = HttpResult(
        ok=True,
        status=200,
        text=json.dumps({"crate": {"id": "serde", "name": "serde"}}),
    )
    mock_json_data = {"crate": {"id": "serde", "name": "serde"}}

    with patch(
        "version_info.registry_cargo.get_json", return_value=(mock_response, mock_json_data)
    ):
        artifact, state = crates_io_latest("serde", timeout_s=10.0)

    assert state == State.error
    assert artifact.value is None
    assert artifact.note == "no max_version in response"


def testcrates_io_latest_generic_error() -> None:
    """Test generic HTTP error handling for crates.io API."""
    mock_response = HttpResult(ok=False, status=500, text="server error", error="HTTP Error 500")

    with patch("version_info.registry_cargo.get_json", return_value=(mock_response, None)):
        artifact, state = crates_io_latest("some-crate", timeout_s=10.0)

    assert state == State.error
    assert artifact.value is None
    assert artifact.note == "HTTP Error 500"


def test_scan_cargo_no_lockfile(tmp_path: Path) -> None:
    """Test scan_cargo when Cargo.lock doesn't exist."""
    section = scan_cargo(str(tmp_path), timeout_s=10.0)

    assert section.title == "Rust (Cargo)"
    assert len(section.rows) == 0


def test_scan_cargo_with_dependencies(tmp_path: Path) -> None:
    """Test full scan with Cargo.lock integration and version comparison."""
    cargo_lock = """
[[package]]
name = "serde"
version = "1.0.190"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.35.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
    """.strip()

    cargo_lock_path = tmp_path / "Cargo.lock"
    cargo_lock_path.write_text(cargo_lock)

    # Mock crates.io responses
    def mock_get_json(url: str, timeout_s: float):
        if "serde" in url:
            return (
                HttpResult(
                    ok=True, status=200, text=json.dumps({"crate": {"max_version": "1.0.195"}})
                ),
                {"crate": {"max_version": "1.0.195"}},
            )
        elif "tokio" in url:
            return (
                HttpResult(
                    ok=True, status=200, text=json.dumps({"crate": {"max_version": "1.35.0"}})
                ),
                {"crate": {"max_version": "1.35.0"}},
            )
        return (HttpResult(ok=False, status=404, text="not found", error="not found"), None)

    with patch("version_info.registry_cargo.get_json", side_effect=mock_get_json):
        section = scan_cargo(str(tmp_path), timeout_s=10.0)

    assert section.title == "Rust (Cargo)"
    assert len(section.rows) == 2

    # serde should show update available
    serde_row = section.rows[0]
    assert serde_row.name == "serde"
    assert serde_row.current.value == "1.0.190"
    assert serde_row.latest.value == "1.0.195"
    assert serde_row.state == State.update_available
    assert serde_row.source == "Cargo.lock"

    # tokio should be up-to-date
    tokio_row = section.rows[1]
    assert tokio_row.name == "tokio"
    assert tokio_row.current.value == "1.35.0"
    assert tokio_row.latest.value == "1.35.0"
    assert tokio_row.state == State.ok
    assert tokio_row.source == "Cargo.lock"


def test_scan_cargo_handles_registry_errors(tmp_path: Path) -> None:
    """Test that registry errors are properly propagated to row state."""
    cargo_lock = """
[[package]]
name = "unknown-crate"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
    """.strip()

    cargo_lock_path = tmp_path / "Cargo.lock"
    cargo_lock_path.write_text(cargo_lock)

    mock_response = HttpResult(ok=False, status=404, text="not found", error="not found")

    with patch("version_info.registry_cargo.get_json", return_value=(mock_response, None)):
        section = scan_cargo(str(tmp_path), timeout_s=10.0)

    assert len(section.rows) == 1
    row = section.rows[0]
    assert row.name == "unknown-crate"
    assert row.state == State.not_found
    assert row.latest.value is None
